### ISSUE TITLE
"Karate: Run" is not getting maven options at settings.json

### ISSUE THREAD

**Issue by tongilcoto** [ivangsa/karate-ide#9]
When using a customised maven settings xml, the "Karate: Run" option at a feature file is not using it

settings.json
```
{
    "karateRunner.karateRunner.default": "_SyncRunner",
    "maven.executable.options": "--settings ~/.m2/settings-eci-nexus.xml",
    "java.configuration.updateBuildConfiguration": "interactive"
}

```
launch.json

```
{
    // Use IntelliSense para saber los atributos posibles.
    // Mantenga el puntero para ver las descripciones de los existentes atributos.
    // Para más información, visite: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "karate-ide",
            "name": "Karate IDE (debug)",
            "request": "launch"
        }
    ]
}
```

Run command:

`> Executing task: mvn clean test -f "/Users/XXXXX/Codigo/YYYYYY/pom.xml" -Dtest=_SyncRunner "-Dkarate.options=/Users/XXXXXX/Codigo/YYYYYY/src/test/java/ZZZZZZZZ/get-zzzzzz.feature:27"  <`

**Comment by ivangsa** [comment]
Hi @tongilcoto 

You are mixing setting from two different plugins
I believe you are using this othe plugin: https://github.com/kirksl/karate-runner

KarateIDE (this plugin) doesn't have a "Karate: Run" button (see screenshot) and it doen't use maven to launch karate tests either
![image](https://user-images.githubusercontent.com/1246876/143391310-49fcf3b5-6f50-44f7-b3b2-c3b6e9bdc233.png)

I recommend you to disable one of the two plugins:

- If you go with KarateIDE, see https://github.com/ivangsa/karate-ide#auto-configuration for configuration details
- If you go with KarateRunner then delete that launch.json file and let KarateRunner regenerate it when you first debug...
